### ISSUE TITLE
Support setting `head` data within route rules

### ISSUE THREAD

**Issue by Flowko** [harlan-zw/nuxt-seo-experiments#14]
### Clear and concise description of the problem

We are currently in the process of transitioning to Nuxt 3 and I am curious about the feasibility of implementing a canonical tag for specific pages. As we have certain routes that lead to identical content, such as `/engagement-rings` and `/engagement-rings/all`, we would like to set the canonical URL for `/engagement-rings/all` to point to `/engagement-rings`. Is this functionality currently available or yet to be developed?

### Suggested solution

Currently, we are retrieving all routes from a specific API endpoint, which provides values for index and sitemap that can be used with our current setup. Additionally, the API returns a canonical value which I am having trouble utilizing. While I understand that I could use useHead to implement the canonical tag, I was hoping to find a way to include it within the same configuration file for the sake of convenience.

I've noticed that we can't remove the canonical tag, and I'm wondering if there's a way to do it using routeRules, but I'm not sure if that's possible.

**Comment by harlan-zw** [comment]
Not sure why I didn't update this issue, but you can do this within route rules.

```ts
export default defineNuxtConfig({
  routeRules: {
    '/about': {
      head: { link: [{ rel: 'canonical', href: 'https://nuxtseo.com/about' }] },
      seoMeta: { title: 'test' },
    },
  },
})
```
