### ISSUE TITLE
Use default meta config to generate Twitter meta tags.

### ISSUE THREAD

**Issue by itsmnthn** [harlan-zw/nuxt-seo-experiments#15]
### Clear and concise description of the problem

```
site: {
    url: 'produrl,
    name: 'sitename',
    title: 'site:title',
    description: 'site:description',
    defaultLocale: 'en',
  },
  app: {
    seoMeta: {
      ogImage: '/img/meta/ogimage.png', // can be any path in public dir or static url with https://...../ogimg.png
      twitterCard: 'summary_large_image',
  }
}
```

With this Nuxt configuration, `og:image`, `twitter:title`, `twitter:description`, `twitter:image` & `twitter:card` is not being generated

### Suggested solution

Suggesting that it should use this config and generate the missing twitter Meta tags as well, if no custom configuration is provided

**Comment by harlan-zw** [comment]
You will need to use the [Nuxt SEO](https://github.com/harlan-zw/nuxt-seo) module if you want this kind of behavior. Inferring tags from site config is not within the scope of this module.

**Comment by itsmnthn** [comment]
I can't seem to find this in the documentation of @nuxtjs/seo adding there would help others too.
