### ISSUE TITLE
Asset alias not resolving in build

### ISSUE THREAD

**Issue by alexkramer98** [harlan-zw/nuxt-seo-experiments#4]
### Describe the bug

When loading a stylesheet via `useHead`, the `~` alias is not resolved at all in the build.

Example:
```vue
<script setup lang="ts">
useHead({
    link: [{
        rel: 'stylesheet',
        href: '~/assets/css/default.css',
    }],
})
</script>
```
This works fine in dev: `~` resolves to `/_nuxt`. 

In the build, it does not transform the `~` alias to anything, and fails loading the asset.

### Reproduction

https://github.com/alexkramer98/nuxt-unhead-alias-bug-repro

1. `yarn install`
2. `yarn build`
3. `yarn preview`

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 19.21 GB / 31.26 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 9.3.0 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.74
    Firefox: 109.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @alexkramer98. Thanks for the issue!

You are right indeed, it is bugged. I'll need to investigate this further as there are some limitations around the imports in the nuxt core.

I've disabled the option by default for the time being

**Comment by alexkramer98** [comment]
Thanks! Any idea what the limitation is in Nuxt? If it's a bug, I'd like to create an issue there.

**Comment by harlan-zw** [comment]
This module no longer has this within the scope there's a bit too much complexity to handle it for now.
